"""Database_20260321

Revision ID: 0f2eb886799b
Revises: 
Create Date: 2026-03-21 18:59:39.330775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2eb886799b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maidata',
    sa.Column('shortid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('genre', sa.Integer(), nullable=False),
    sa.Column('cabinet', sa.Enum('SD', 'DX', native_enum=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('version_cn', sa.Integer(), nullable=True),
    sa.Column('converter', sa.String(), nullable=True),
    sa.Column('zip_path', sa.String(), nullable=False),
    sa.Column('is_utage', sa.Boolean(), nullable=False),
    sa.Column('utage_tag', sa.String(), nullable=False),
    sa.Column('buddy', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('shortid', name=op.f('pk_maidata'))
    )
    with op.batch_alter_table('maidata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maidata_is_utage'), ['is_utage'], unique=False)
        batch_op.create_index(batch_op.f('ix_maidata_title'), ['title'], unique=False)

    op.create_table('aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shortid', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('create_qq', sa.Integer(), nullable=False),
    sa.Column('create_qq_group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shortid'], ['maidata.shortid'], name=op.f('fk_aliases_shortid_maidata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aliases')),
    sa.UniqueConstraint('shortid', 'alias', name=op.f('uq_aliases_shortid'))
    )
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aliases_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_aliases_shortid'), ['shortid'], unique=False)

    op.create_table('charts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shortid', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('lv', sa.Float(), nullable=False),
    sa.Column('lv_cn', sa.Float(), nullable=True),
    sa.Column('lv_synh', sa.Float(), nullable=True),
    sa.Column('des', sa.String(), nullable=False),
    sa.Column('inote', sa.String(), nullable=False),
    sa.Column('note_count_tap', sa.Integer(), nullable=False),
    sa.Column('note_count_hold', sa.Integer(), nullable=False),
    sa.Column('note_count_slide', sa.Integer(), nullable=False),
    sa.Column('note_count_touch', sa.Integer(), nullable=False),
    sa.Column('note_count_break', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shortid'], ['maidata.shortid'], name=op.f('fk_charts_shortid_maidata'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charts')),
    sa.UniqueConstraint('shortid', 'difficulty', name=op.f('uq_charts_shortid'))
    )
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charts_lv'), ['lv'], unique=False)
        batch_op.create_index(batch_op.f('ix_charts_lv_cn'), ['lv_cn'], unique=False)
        batch_op.create_index(batch_op.f('ix_charts_lv_synh'), ['lv_synh'], unique=False)

    op.create_table('chart_achs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shortid', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('server', sa.Enum('JP', 'INTL', 'CN', native_enum=False), nullable=False),
    sa.Column('achievement', sa.Float(), nullable=False),
    sa.Column('dxscore', sa.Integer(), nullable=False),
    sa.Column('combo', sa.Integer(), nullable=False),
    sa.Column('sync', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], name=op.f('fk_chart_achs_chart_id_charts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shortid'], ['maidata.shortid'], name=op.f('fk_chart_achs_shortid_maidata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chart_achs')),
    sa.UniqueConstraint('shortid', 'difficulty', 'server', name=op.f('uq_chart_achs_shortid'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chart_achs')
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charts_lv_synh'))
        batch_op.drop_index(batch_op.f('ix_charts_lv_cn'))
        batch_op.drop_index(batch_op.f('ix_charts_lv'))

    op.drop_table('charts')
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aliases_shortid'))
        batch_op.drop_index(batch_op.f('ix_aliases_alias'))

    op.drop_table('aliases')
    with op.batch_alter_table('maidata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maidata_title'))
        batch_op.drop_index(batch_op.f('ix_maidata_is_utage'))

    op.drop_table('maidata')
    # ### end Alembic commands ###
