"""empty message

Revision ID: 2f098106901e
Revises: 3c7d20d5131d
Create Date: 2026-06-20 21:57:42.392821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f098106901e'
down_revision = '3c7d20d5131d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maib_maidatas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tg_file_id_cache', sa.String(), nullable=True))

    with op.batch_alter_table('maib_maiusers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_telegram_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_maib_maiusers_user_telegram_id'), ['user_telegram_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maib_maiusers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maib_maiusers_user_telegram_id'))
        batch_op.drop_column('user_telegram_id')

    with op.batch_alter_table('maib_maidatas', schema=None) as batch_op:
        batch_op.drop_column('tg_file_id_cache')

    # ### end Alembic commands ###
