"""empty message

Revision ID: 3c7d20d5131d
Revises: 7b2d13f1aa77
Create Date: 2026-05-13 23:42:32.163286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7d20d5131d'
down_revision = '7b2d13f1aa77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maib_maiusers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jp_dxrating_b35_first', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('jp_dxrating_b35_last', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('jp_dxrating_b15_first', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('jp_dxrating_b15_last', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cn_dxrating_b35_first', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cn_dxrating_b35_last', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cn_dxrating_b15_first', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cn_dxrating_b15_last', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maib_maiusers', schema=None) as batch_op:
        batch_op.drop_column('cn_dxrating_b15_last')
        batch_op.drop_column('cn_dxrating_b15_first')
        batch_op.drop_column('cn_dxrating_b35_last')
        batch_op.drop_column('cn_dxrating_b35_first')
        batch_op.drop_column('jp_dxrating_b15_last')
        batch_op.drop_column('jp_dxrating_b15_first')
        batch_op.drop_column('jp_dxrating_b35_last')
        batch_op.drop_column('jp_dxrating_b35_first')

    # ### end Alembic commands ###
