"""empty message

Revision ID: 46a7e975482a
Revises: 
Create Date: 2026-04-25 19:54:59.456197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a7e975482a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maib_maidatas',
    sa.Column('shortid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('genre', sa.Integer(), nullable=False),
    sa.Column('cabinet', sa.Enum('SD', 'DX', native_enum=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('version_cn', sa.Integer(), nullable=True),
    sa.Column('converter', sa.String(), nullable=True),
    sa.Column('zip_path', sa.String(), nullable=False),
    sa.Column('is_utage', sa.Boolean(), nullable=False),
    sa.Column('utage_tag', sa.String(), nullable=False),
    sa.Column('buddy', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('shortid', name=op.f('pk_maib_maidatas'))
    )
    with op.batch_alter_table('maib_maidatas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maib_maidatas_is_utage'), ['is_utage'], unique=False)
        batch_op.create_index(batch_op.f('ix_maib_maidatas_title'), ['title'], unique=False)

    op.create_table('maib_maiusers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('default_server', sa.Enum('JP', 'CN', native_enum=False), nullable=False),
    sa.Column('plate_version', sa.Integer(), nullable=True),
    sa.Column('plate_code', sa.Integer(), nullable=True),
    sa.Column('jp_update_time', sa.Integer(), nullable=False),
    sa.Column('jp_dxrating', sa.Integer(), nullable=False),
    sa.Column('cn_update_time', sa.Integer(), nullable=False),
    sa.Column('cn_dxrating', sa.Integer(), nullable=False),
    sa.Column('sync_hash', sa.String(), nullable=True),
    sa.Column('sync_allow_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_maib_maiusers'))
    )
    op.create_table('maib_maialiases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shortid', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('create_qq', sa.Integer(), nullable=False),
    sa.Column('create_qq_group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shortid'], ['maib_maidatas.shortid'], name=op.f('fk_maib_maialiases_shortid_maib_maidatas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maib_maialiases')),
    sa.UniqueConstraint('shortid', 'alias', name=op.f('uq_maib_maialiases_shortid'))
    )
    with op.batch_alter_table('maib_maialiases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maib_maialiases_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_maib_maialiases_shortid'), ['shortid'], unique=False)

    op.create_table('maib_maicharts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shortid', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('lv', sa.Float(), nullable=False),
    sa.Column('lv_cn', sa.Float(), nullable=True),
    sa.Column('lv_synh', sa.Float(), nullable=True),
    sa.Column('des', sa.String(), nullable=False),
    sa.Column('inote', sa.String(), nullable=False),
    sa.Column('note_count_tap', sa.Integer(), nullable=False),
    sa.Column('note_count_hold', sa.Integer(), nullable=False),
    sa.Column('note_count_slide', sa.Integer(), nullable=False),
    sa.Column('note_count_touch', sa.Integer(), nullable=False),
    sa.Column('note_count_break', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shortid'], ['maib_maidatas.shortid'], name=op.f('fk_maib_maicharts_shortid_maib_maidatas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maib_maicharts')),
    sa.UniqueConstraint('shortid', 'difficulty', name=op.f('uq_maib_maicharts_shortid'))
    )
    with op.batch_alter_table('maib_maicharts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maib_maicharts_lv'), ['lv'], unique=False)
        batch_op.create_index(batch_op.f('ix_maib_maicharts_lv_cn'), ['lv_cn'], unique=False)
        batch_op.create_index(batch_op.f('ix_maib_maicharts_lv_synh'), ['lv_synh'], unique=False)

    op.create_table('maib_maichartachs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shortid', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('server', sa.Enum('JP', 'CN', native_enum=False), nullable=False),
    sa.Column('achievement', sa.Float(), nullable=False),
    sa.Column('dxscore', sa.Integer(), nullable=False),
    sa.Column('combo', sa.Integer(), nullable=False),
    sa.Column('sync', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.Column('dxrating', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chart_id'], ['maib_maicharts.id'], name=op.f('fk_maib_maichartachs_chart_id_maib_maicharts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shortid'], ['maib_maidatas.shortid'], name=op.f('fk_maib_maichartachs_shortid_maib_maidatas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maib_maichartachs')),
    sa.UniqueConstraint('user_id', 'shortid', 'difficulty', 'server', name=op.f('uq_maib_maichartachs_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maib_maichartachs')
    with op.batch_alter_table('maib_maicharts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maib_maicharts_lv_synh'))
        batch_op.drop_index(batch_op.f('ix_maib_maicharts_lv_cn'))
        batch_op.drop_index(batch_op.f('ix_maib_maicharts_lv'))

    op.drop_table('maib_maicharts')
    with op.batch_alter_table('maib_maialiases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maib_maialiases_shortid'))
        batch_op.drop_index(batch_op.f('ix_maib_maialiases_alias'))

    op.drop_table('maib_maialiases')
    op.drop_table('maib_maiusers')
    with op.batch_alter_table('maib_maidatas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maib_maidatas_title'))
        batch_op.drop_index(batch_op.f('ix_maib_maidatas_is_utage'))

    op.drop_table('maib_maidatas')
    # ### end Alembic commands ###
