"""initial_migration

Revision ID: 7044d85a4570
Revises: 
Create Date: 2026-03-20 16:50:33.134970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7044d85a4570'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_achs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shortid', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('server', sa.Enum('JP', 'INTL', 'CN', native_enum=False), nullable=False),
    sa.Column('achievement', sa.Float(), nullable=False),
    sa.Column('dxscore', sa.Integer(), nullable=False),
    sa.Column('combo', sa.Integer(), nullable=False),
    sa.Column('sync', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shortid'], ['maidata.shortid'], name=op.f('fk_chart_achs_shortid_maidata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chart_achs')),
    sa.UniqueConstraint('shortid', 'difficulty', name=op.f('uq_chart_achs_shortid'))
    )
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_aliases_shortid'), ['shortid', 'alias'])

    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lv_cn', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lv_synh', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_charts_lv_cn'), ['lv_cn'], unique=False)
        batch_op.create_index(batch_op.f('ix_charts_lv_synh'), ['lv_synh'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_charts_shortid'), ['shortid', 'difficulty'])

    with op.batch_alter_table('maidata', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('zip_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('utage_tag',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('buddy',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maidata', schema=None) as batch_op:
        batch_op.alter_column('buddy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('utage_tag',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('zip_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('genre',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_charts_shortid'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_charts_lv_synh'))
        batch_op.drop_index(batch_op.f('ix_charts_lv_cn'))
        batch_op.drop_column('lv_synh')
        batch_op.drop_column('lv_cn')

    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_aliases_shortid'), type_='unique')

    op.drop_table('chart_achs')
    # ### end Alembic commands ###
