"""empty message

Revision ID: 79755df583d2
Revises: 91f4b7918c4a
Create Date: 2026-08-11 01:21:19.642385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79755df583d2'
down_revision = '91f4b7918c4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maib_maimes',
    sa.Column('access', sa.String(length=16), nullable=False, comment='Aime卡号'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户id'),
    sa.Column('access4', sa.String(length=4), nullable=False, comment='Aime卡号后四位缓存'),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('access', name=op.f('pk_maib_maimes'))
    )
    with op.batch_alter_table('maib_maimes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maib_maimes_access4'), ['access4'], unique=False)
        batch_op.create_index(batch_op.f('ix_maib_maimes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maib_maimes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maib_maimes_user_id'))
        batch_op.drop_index(batch_op.f('ix_maib_maimes_access4'))

    op.drop_table('maib_maimes')
    # ### end Alembic commands ###
