"""empty message

Revision ID: 815e1264b416
Revises: 0f2eb886799b
Create Date: 2026-03-22 15:24:49.907929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815e1264b416'
down_revision = '0f2eb886799b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_achs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dxrating', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_chart_achs_shortid'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_chart_achs_user_id'), ['user_id', 'shortid', 'difficulty', 'server'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_achs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_chart_achs_user_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_chart_achs_shortid'), ['shortid', 'difficulty', 'server'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('dxrating')

    # ### end Alembic commands ###
