"""empty message

Revision ID: 82b34846262c
Revises: 0a1b2c3d4e5f
Create Date: 2026-09-20 20:21:40.526393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b34846262c'
down_revision = '0a1b2c3d4e5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maib_maichartachs', schema=None) as batch_op:
        batch_op.alter_column('server',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=4),
               existing_nullable=False)

    with op.batch_alter_table('maib_mairecords', schema=None) as batch_op:
        batch_op.alter_column('server',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=4),
               existing_nullable=False)

    with op.batch_alter_table('maib_maiusers', schema=None) as batch_op:
        batch_op.alter_column('default_server',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maib_maiusers', schema=None) as batch_op:
        batch_op.alter_column('default_server',
               existing_type=sa.String(length=4),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)

    with op.batch_alter_table('maib_mairecords', schema=None) as batch_op:
        batch_op.alter_column('server',
               existing_type=sa.String(length=4),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('maib_maichartachs', schema=None) as batch_op:
        batch_op.alter_column('server',
               existing_type=sa.String(length=4),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)

    # ### end Alembic commands ###
