"""唯一约束加入 server 标识

Revision ID: 934c1df57bdc
Revises: 7044d85a4570
Create Date: 2026-03-21 12:15:38.112696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934c1df57bdc'
down_revision = '7044d85a4570'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_achs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_chart_achs_shortid'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_chart_achs_shortid'), ['shortid', 'difficulty', 'server'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_achs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_chart_achs_shortid'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_chart_achs_shortid'), ['shortid', 'difficulty'])

    # ### end Alembic commands ###
