"""empty message

Revision ID: fa004c568421
Revises: 0093ec4169e8
Create Date: 2026-04-28 20:33:26.606909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa004c568421'
down_revision = '0093ec4169e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maib_idchecks',
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('mapped_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('original_id', name=op.f('pk_maib_idchecks'))
    )
    with op.batch_alter_table('maib_idchecks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maib_idchecks_mapped_id'), ['mapped_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maib_idchecks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maib_idchecks_mapped_id'))

    op.drop_table('maib_idchecks')
    # ### end Alembic commands ###
