"""empty message

Revision ID: 8c9127af8c4d
Revises: 
Create Date: 2026-05-15 21:55:28.692770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9127af8c4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bakamai_whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bakamai_whitelist')),
    sa.UniqueConstraint('user_id', 'group_id', 'platform', name=op.f('uq_bakamai_whitelist_user_id'))
    )
    with op.batch_alter_table('bakamai_whitelist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bakamai_whitelist_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bakamai_whitelist_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakamai_whitelist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bakamai_whitelist_user_id'))
        batch_op.drop_index(batch_op.f('ix_bakamai_whitelist_group_id'))

    op.drop_table('bakamai_whitelist')
    # ### end Alembic commands ###
