"""empty message

Revision ID: ae2b5e023a59
Revises: f1d13f9d55b7
Create Date: 2026-07-03 10:56:23.943186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2b5e023a59'
down_revision = 'f1d13f9d55b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_partner_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False, comment='平台标识)'),
    sa.Column('group_id', sa.String(length=50), nullable=False),
    sa.Column('filter_activate', sa.Boolean(), nullable=False, comment='是否启用活跃过滤器，若开启则根据配置文件筛选活跃用户'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_partner_group')),
    sa.UniqueConstraint('platform', 'group_id', name='uq_group_platform_id')
    )
    with op.batch_alter_table('daily_partner_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_partner_group_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_partner_group_platform'), ['platform'], unique=False)

    with op.batch_alter_table('daily_partner_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_partner_record_husband_id'), ['husband_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_partner_record_wife_id'), ['wife_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_partner_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_partner_record_wife_id'))
        batch_op.drop_index(batch_op.f('ix_daily_partner_record_husband_id'))

    with op.batch_alter_table('daily_partner_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_partner_group_platform'))
        batch_op.drop_index(batch_op.f('ix_daily_partner_group_group_id'))

    op.drop_table('daily_partner_group')
    # ### end Alembic commands ###
