"""empty message

Revision ID: fe62315a285e
Revises: 
Create Date: 2026-06-28 15:39:48.913659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe62315a285e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_partner_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False, comment='记录日期'),
    sa.Column('platform', sa.String(length=50), nullable=False, comment='平台标识'),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('relation_type', sa.Integer(), nullable=False, comment='关系类型，0: 老婆, 1: 老公'),
    sa.Column('swap_count', sa.Integer(), nullable=False, comment='独立记录 user_id 的换人次数'),
    sa.Column('is_divorced', sa.Boolean(), nullable=False, comment='离婚惩罚状态'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_partner_record')),
    sa.UniqueConstraint('record_date', 'platform', 'group_id', 'user_id', 'relation_type', name='uq_daily_relation')
    )
    with op.batch_alter_table('daily_partner_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_partner_record_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_partner_record_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_partner_record_record_date'), ['record_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_partner_record_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_partner_record_user_id'), ['user_id'], unique=False)

    op.create_table('daily_partner_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False, comment='平台标识)'),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否可使用插件，若为否则无法被其他人选中'),
    sa.Column('is_bot', sa.Boolean(), nullable=False, comment='是否为 bot'),
    sa.Column('allow_bot', sa.Boolean(), nullable=False, comment='是否允许抽选选择 bot，是否为 bot 参照`is_bot`确定'),
    sa.Column('hope_id', sa.BigInteger(), nullable=True, comment='心愿单，记录抽选心选对象，抽选 wife 时抽到的概率更高'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_partner_user')),
    sa.UniqueConstraint('platform', 'user_id', name='uq_user_platform_id')
    )
    with op.batch_alter_table('daily_partner_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_partner_user_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_partner_user_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_partner_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_partner_user_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_partner_user_platform'))

    op.drop_table('daily_partner_user')
    with op.batch_alter_table('daily_partner_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_partner_record_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_partner_record_target_id'))
        batch_op.drop_index(batch_op.f('ix_daily_partner_record_record_date'))
        batch_op.drop_index(batch_op.f('ix_daily_partner_record_platform'))
        batch_op.drop_index(batch_op.f('ix_daily_partner_record_group_id'))

    op.drop_table('daily_partner_record')
    # ### end Alembic commands ###
