"""empty message

Revision ID: 446ddcfd530a
Revises: 69e95093dbe8
Create Date: 2026-04-29 23:35:44.808734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446ddcfd530a'
down_revision = '69e95093dbe8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatfood_user_ban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('ban_time', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatfood_user_ban')),
    sa.UniqueConstraint('user_id', 'group_id', name=op.f('uq_whatfood_user_ban_user_id'))
    )
    with op.batch_alter_table('whatfood_user_ban', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatfood_user_ban_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatfood_user_ban_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('whatfood_item', schema=None) as batch_op:
        batch_op.alter_column('create_qq',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('whatfood_score', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('whatfood_user_pref', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatfood_user_pref', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('whatfood_score', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('whatfood_item', schema=None) as batch_op:
        batch_op.alter_column('create_qq',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('whatfood_user_ban', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatfood_user_ban_user_id'))
        batch_op.drop_index(batch_op.f('ix_whatfood_user_ban_group_id'))

    op.drop_table('whatfood_user_ban')
    # ### end Alembic commands ###
