"""init_what_food

Revision ID: 69e95093dbe8
Revises: 
Create Date: 2026-03-25 12:27:27.102089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e95093dbe8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatfood_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('Food', 'Drink', native_enum=False), nullable=False),
    sa.Column('is_wine', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('create_qq', sa.Integer(), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('total_weighted_sum', sa.Integer(), nullable=False),
    sa.Column('total_weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatfood_item'))
    )
    with op.batch_alter_table('whatfood_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatfood_item_name'), ['name'], unique=True)

    op.create_table('whatfood_user_pref',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('offset', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_whatfood_user_pref'))
    )
    op.create_table('whatfood_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['whatfood_item.id'], name=op.f('fk_whatfood_score_item_id_whatfood_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatfood_score')),
    sa.UniqueConstraint('item_id', 'user_id', name=op.f('uq_whatfood_score_item_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatfood_score')
    op.drop_table('whatfood_user_pref')
    with op.batch_alter_table('whatfood_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatfood_item_name'))

    op.drop_table('whatfood_item')
    # ### end Alembic commands ###
